// Defines the structure of the SecureEnvelope used for end-to-end
// encrypted messaging.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: src/action_intention/envelope/v1/secure-envelope.proto

package sm_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents the secure data packet sent between users via the routing service.
// all the id fields are actually urns but we just call them id
type SecureEnvelopePb struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URN of the message sender (e.g., "urn:sm:user:user-a@example.com").
	SenderId string `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// The URN of the message recipient.
	RecipientId string `protobuf:"bytes,2,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	// A unique identifier for the message.
	MessageId string `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	GroupId   string `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// A unique identifier for the conversation.
	ConversationId string `protobuf:"bytes,5,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// The AES-encrypted payload.
	EncryptedData []byte `protobuf:"bytes,6,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	// An AES-encrypted snippet of the full payload
	EncryptedSnippet []byte `protobuf:"bytes,7,opt,name=encrypted_snippet,json=encryptedSnippet,proto3" json:"encrypted_snippet,omitempty"`
	// The RSA-encrypted AES symmetric key.
	EncryptedSymmetricKey []byte `protobuf:"bytes,8,opt,name=encrypted_symmetric_key,json=encryptedSymmetricKey,proto3" json:"encrypted_symmetric_key,omitempty"`
	// The signature of the EncryptedData.
	Signature     []byte `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecureEnvelopePb) Reset() {
	*x = SecureEnvelopePb{}
	mi := &file_src_action_intention_envelope_v1_secure_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecureEnvelopePb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecureEnvelopePb) ProtoMessage() {}

func (x *SecureEnvelopePb) ProtoReflect() protoreflect.Message {
	mi := &file_src_action_intention_envelope_v1_secure_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecureEnvelopePb.ProtoReflect.Descriptor instead.
func (*SecureEnvelopePb) Descriptor() ([]byte, []int) {
	return file_src_action_intention_envelope_v1_secure_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *SecureEnvelopePb) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SecureEnvelopePb) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *SecureEnvelopePb) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SecureEnvelopePb) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SecureEnvelopePb) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SecureEnvelopePb) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *SecureEnvelopePb) GetEncryptedSnippet() []byte {
	if x != nil {
		return x.EncryptedSnippet
	}
	return nil
}

func (x *SecureEnvelopePb) GetEncryptedSymmetricKey() []byte {
	if x != nil {
		return x.EncryptedSymmetricKey
	}
	return nil
}

func (x *SecureEnvelopePb) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// A wrapper message for a list of secure envelopes.
type SecureEnvelopeListPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelopes     []*SecureEnvelopePb    `protobuf:"bytes,1,rep,name=envelopes,proto3" json:"envelopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecureEnvelopeListPb) Reset() {
	*x = SecureEnvelopeListPb{}
	mi := &file_src_action_intention_envelope_v1_secure_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecureEnvelopeListPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecureEnvelopeListPb) ProtoMessage() {}

func (x *SecureEnvelopeListPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_action_intention_envelope_v1_secure_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecureEnvelopeListPb.ProtoReflect.Descriptor instead.
func (*SecureEnvelopeListPb) Descriptor() ([]byte, []int) {
	return file_src_action_intention_envelope_v1_secure_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *SecureEnvelopeListPb) GetEnvelopes() []*SecureEnvelopePb {
	if x != nil {
		return x.Envelopes
	}
	return nil
}

var File_src_action_intention_envelope_v1_secure_envelope_proto protoreflect.FileDescriptor

const file_src_action_intention_envelope_v1_secure_envelope_proto_rawDesc = "" +
	"\n" +
	"6src/action_intention/envelope/v1/secure-envelope.proto\x12\x1caction_intention.envelope.v1\"\xdf\x02\n" +
	"\x10SecureEnvelopePb\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12!\n" +
	"\frecipient_id\x18\x02 \x01(\tR\vrecipientId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\tR\agroupId\x12'\n" +
	"\x0fconversation_id\x18\x05 \x01(\tR\x0econversationId\x12%\n" +
	"\x0eencrypted_data\x18\x06 \x01(\fR\rencryptedData\x12+\n" +
	"\x11encrypted_snippet\x18\a \x01(\fR\x10encryptedSnippet\x126\n" +
	"\x17encrypted_symmetric_key\x18\b \x01(\fR\x15encryptedSymmetricKey\x12\x1c\n" +
	"\tsignature\x18\t \x01(\fR\tsignature\"d\n" +
	"\x14SecureEnvelopeListPb\x12L\n" +
	"\tenvelopes\x18\x01 \x03(\v2..action_intention.envelope.v1.SecureEnvelopePbR\tenvelopesBIZGgithub.com/illmade-knight/go-action-intention-protos/gen/go/sm/v1;sm_v1b\x06proto3"

var (
	file_src_action_intention_envelope_v1_secure_envelope_proto_rawDescOnce sync.Once
	file_src_action_intention_envelope_v1_secure_envelope_proto_rawDescData []byte
)

func file_src_action_intention_envelope_v1_secure_envelope_proto_rawDescGZIP() []byte {
	file_src_action_intention_envelope_v1_secure_envelope_proto_rawDescOnce.Do(func() {
		file_src_action_intention_envelope_v1_secure_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_action_intention_envelope_v1_secure_envelope_proto_rawDesc), len(file_src_action_intention_envelope_v1_secure_envelope_proto_rawDesc)))
	})
	return file_src_action_intention_envelope_v1_secure_envelope_proto_rawDescData
}

var file_src_action_intention_envelope_v1_secure_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_action_intention_envelope_v1_secure_envelope_proto_goTypes = []any{
	(*SecureEnvelopePb)(nil),     // 0: action_intention.envelope.v1.SecureEnvelopePb
	(*SecureEnvelopeListPb)(nil), // 1: action_intention.envelope.v1.SecureEnvelopeListPb
}
var file_src_action_intention_envelope_v1_secure_envelope_proto_depIdxs = []int32{
	0, // 0: action_intention.envelope.v1.SecureEnvelopeListPb.envelopes:type_name -> action_intention.envelope.v1.SecureEnvelopePb
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_action_intention_envelope_v1_secure_envelope_proto_init() }
func file_src_action_intention_envelope_v1_secure_envelope_proto_init() {
	if File_src_action_intention_envelope_v1_secure_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_action_intention_envelope_v1_secure_envelope_proto_rawDesc), len(file_src_action_intention_envelope_v1_secure_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_action_intention_envelope_v1_secure_envelope_proto_goTypes,
		DependencyIndexes: file_src_action_intention_envelope_v1_secure_envelope_proto_depIdxs,
		MessageInfos:      file_src_action_intention_envelope_v1_secure_envelope_proto_msgTypes,
	}.Build()
	File_src_action_intention_envelope_v1_secure_envelope_proto = out.File
	file_src_action_intention_envelope_v1_secure_envelope_proto_goTypes = nil
	file_src_action_intention_envelope_v1_secure_envelope_proto_depIdxs = nil
}
