// File: libs/messenger/protos/src/types/messenger/v1/payload.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: src/messenger/message/v1/payload.proto

// Package name mirrors the directory structure from the 'src/' root

package messenger_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EncryptedMessagePayloadPb defines the *inner* payload that is
// encrypted and placed inside the SecureEnvelope's 'encrypted_data' field.
//
// This is the "sealed" part of the "Sealed Sender" model.
type EncryptedMessagePayloadPb struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URN of the *sender*.
	SenderId string `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// The ISO 8601 timestamp of when the message was sent (by the sender).
	SentTimestamp string `protobuf:"bytes,2,opt,name=sent_timestamp,json=sentTimestamp,proto3" json:"sent_timestamp,omitempty"`
	// The URN that identifies the *type* of the payloadBytes.
	// e.g., "urn:sm:type:text-message", "urn:sm:type:reaction"
	TypeId string `protobuf:"bytes,3,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	// The raw, type-specific payload.
	// (e.g., for a text message, this would be the UTF-8 bytes of the string).
	PayloadBytes  []byte `protobuf:"bytes,4,opt,name=payload_bytes,json=payloadBytes,proto3" json:"payload_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedMessagePayloadPb) Reset() {
	*x = EncryptedMessagePayloadPb{}
	mi := &file_src_messenger_message_v1_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedMessagePayloadPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedMessagePayloadPb) ProtoMessage() {}

func (x *EncryptedMessagePayloadPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_messenger_message_v1_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedMessagePayloadPb.ProtoReflect.Descriptor instead.
func (*EncryptedMessagePayloadPb) Descriptor() ([]byte, []int) {
	return file_src_messenger_message_v1_payload_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptedMessagePayloadPb) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *EncryptedMessagePayloadPb) GetSentTimestamp() string {
	if x != nil {
		return x.SentTimestamp
	}
	return ""
}

func (x *EncryptedMessagePayloadPb) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *EncryptedMessagePayloadPb) GetPayloadBytes() []byte {
	if x != nil {
		return x.PayloadBytes
	}
	return nil
}

var File_src_messenger_message_v1_payload_proto protoreflect.FileDescriptor

const file_src_messenger_message_v1_payload_proto_rawDesc = "" +
	"\n" +
	"&src/messenger/message/v1/payload.proto\x12\x16src.types.messenger.v1\"\x9d\x01\n" +
	"\x19EncryptedMessagePayloadPb\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12%\n" +
	"\x0esent_timestamp\x18\x02 \x01(\tR\rsentTimestamp\x12\x17\n" +
	"\atype_id\x18\x03 \x01(\tR\x06typeId\x12#\n" +
	"\rpayload_bytes\x18\x04 \x01(\fR\fpayloadBytesBLZJgithub.com/tinywideclouds/gen-messenger/go/types/messenger/v1;messenger_v1b\x06proto3"

var (
	file_src_messenger_message_v1_payload_proto_rawDescOnce sync.Once
	file_src_messenger_message_v1_payload_proto_rawDescData []byte
)

func file_src_messenger_message_v1_payload_proto_rawDescGZIP() []byte {
	file_src_messenger_message_v1_payload_proto_rawDescOnce.Do(func() {
		file_src_messenger_message_v1_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_messenger_message_v1_payload_proto_rawDesc), len(file_src_messenger_message_v1_payload_proto_rawDesc)))
	})
	return file_src_messenger_message_v1_payload_proto_rawDescData
}

var file_src_messenger_message_v1_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_src_messenger_message_v1_payload_proto_goTypes = []any{
	(*EncryptedMessagePayloadPb)(nil), // 0: src.types.messenger.v1.EncryptedMessagePayloadPb
}
var file_src_messenger_message_v1_payload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_messenger_message_v1_payload_proto_init() }
func file_src_messenger_message_v1_payload_proto_init() {
	if File_src_messenger_message_v1_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_messenger_message_v1_payload_proto_rawDesc), len(file_src_messenger_message_v1_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_messenger_message_v1_payload_proto_goTypes,
		DependencyIndexes: file_src_messenger_message_v1_payload_proto_depIdxs,
		MessageInfos:      file_src_messenger_message_v1_payload_proto_msgTypes,
	}.Build()
	File_src_messenger_message_v1_payload_proto = out.File
	file_src_messenger_message_v1_payload_proto_goTypes = nil
	file_src_messenger_message_v1_payload_proto_depIdxs = nil
}
